---
- hosts: appservers
  become: no
  gather_facts: no
  tasks:
    - include_vars:
        file: roles/common/vars/main.yml
    - include_vars:
        file: roles/appserver/vars/main.yml
    - set_fact:
        ansible_port: "{{ ubuntu_common_ssh_port }}"

- hosts: appservers
  become: yes
  tasks:
    - import_role:
        name: appserver
...
